on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 8
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '8'
            cache: 'gradle'
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3
        - name: Build with Gradle
          run: gradle build
        - name: Assess code formatting
          run: gradle spotlessCheck
        - name: Test
          run: gradlew test
