on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 8
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '8'
            cache: 'gradle'
        - name: Assess code formatting
          run: ./gradlew spotlessCheck --no-daemon
        - name: Build with Gradle
          run: ./gradlew build --no-daemon
        - name: Test
          run: ./gradlew test --no-daemon
